### ISSUE TITLE
Remove cats dependency

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/fp-foundation#22]
I believe the only blocker is `Eq`, we will have to create a local version

**Comment by phderome** [comment]
NonEmptyList, foldMap easy to replace? e.g. https://julien-truffaut.github.io/fp-foundation/Type.html#19. And then later Functors, Monoids...

From my perspective, it looks rather difficult. I also don't see a problem with a Cats dependency as it may well be familiar to many students (and if not they will probably come to learn it at the same time).

**Comment by phderome** [comment]
I had a little crack at it and it seems a bit difficult and not only tedious for me. I copied your basic Eq definitions from slides and that helps. But then there are all kinds of requirements for derived classes that become problematic.

See current errors below for example with first crack at solution below that is clearly not sufficient. I don't know what the All.scala solution does but it clearly accomplishes a lot of good work with `getAll` and `Eq.by`.

[info] No tests to run for slides / Test / testOnly
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:103:30: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[List[Boolean]]
[error]   checkAll("List", monoidLaws[List[Boolean]])
[error]                              ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:104:32: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[Vector[Boolean]]
[error]   checkAll("Vector", monoidLaws[Vector[Boolean]])
[error]                                ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:105:29: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[Set[Int]]
[error]   checkAll("Set", monoidLaws[Set[Int]])
[error]                             ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:106:32: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[(Int, String)]
[error]   checkAll("Tuple2", monoidLaws[(Int, String)])
[error]                                ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:107:32: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[Option[Int]]
[error]   checkAll("Option", monoidLaws[Option[Int]])
[error]                                ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:108:29: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[Map[Int,String]]
[error]   checkAll("Map", monoidLaws[Map[Int, String]])
[error]                             ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:120:33: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.Product]
[error]   checkAll("Product", monoidLaws[Product])
[error]                                 ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:121:29: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.All]
[error]   checkAll("All", monoidLaws[All])
[error]                             ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:122:30: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.Endo[Int]]
[error]   checkAll("Endo", monoidLaws[Endo[Int]])
[error]                              ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:133:41: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[cats.data.NonEmptyList[Boolean]]
[error]   checkAll("NonEmptyList", semigroupLaws[NonEmptyList[Boolean]])
[error]                                         ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:135:32: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.Min[Int]]
[error]   checkAll("Min", semigroupLaws[Min[Int]])
[error]                                ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:141:34: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.First[Int]]
[error]   checkAll("First", semigroupLaws[First[Int]])
[error]                                  ^
[error] /Users/philippederome/workspace/fp-foundation/exercises/src/test/scala/typeclass/TypeclassTest.scala:147:33: could not find implicit value for evidence parameter of type exercises.typeclass.Eq[exercises.typeclass.Dual[Int]]
[error]   checkAll("Dual", semigroupLaws[Dual[Int]])
[error]                                 ^
[error] 13 errors found

```

trait Eq[A] {
  def eqv(x: A, y: A): Boolean
  def neqv(x: A, y: A): Boolean = !eqv(x, y)
}

object Eq {
  def apply[A](implicit ev: Eq[A]): Eq[A] = ev

  object syntax {
    implicit class EqSyntax[A](self: A) {
      def eqv(other: A)(implicit ev: Eq[A]): Boolean =
        ev.eqv(self, other)
      def ===(other: A)(implicit ev: Eq[A]): Boolean = eqv(other)
      def neqv(other: A)(implicit ev: Eq[A]): Boolean = !eqv(other)
    }
  }

  implicit val intEq: Eq[Int] = new Eq[Int] {
    def eqv(x: Int, y: Int): Boolean = x == y
  }

  implicit val dblEq: Eq[Double] = new Eq[Double] {
    def eqv(x: Double, y: Double): Boolean = x == y
  }

  implicit val unitEq: Eq[Unit] = new Eq[Unit] {
    def eqv(x: Unit, y: Unit): Boolean = true
  }

  implicit val boolEq: Eq[Boolean] = new Eq[Boolean] {
    def eqv(x: Boolean, y: Boolean): Boolean = x == y
  }

  implicit val stringEq: Eq[String] = new Eq[String] {
    def eqv(x: String, y: String): Boolean = x == y
  }
}

```

**Comment by phderome** [comment]
There is also NEL to implement in addition to Eq.

**Comment by julien-truffaut** [comment]
Good point about NEL. Now I am thinking it is probably fine to keep cats dependency for NEL and maybe for usage in more advance chapters.

I still think it worth it to have our own `Eq` implementation, I am afraid users with no scala background will find it confusing in early chapter.

Regarding the errors you had, I believe you are missing a couple of implicit:
* `List`, `Vecotr`, `Set`, `Tuple2`, `Option`, `Map`, `NonEmptyList` to be defined in companion object of `Eq`
* `Dual`, `First`, `Min`, `Endo` in their companion object like https://github.com/julien-truffaut/fp-foundation/blob/master/exercises/src/main/scala/exercises/typeclass/Dual.scala#L8

**Comment by phderome** [comment]
I implemented most of those now, and I have only two errors left. Complication that remains is about `IsoLaws` and `Iso`. We cannot compare Scala functions for `Eq`, can we? ;-)

Maybe you need to remove your reliance on `cats.implicits._` (and import only cats Eq) as a preliminary step before this works? You use `some` a lot for instance and if I remove `cats.implicits` I get tons of errors. But if I keep it, there are only two left. How can we fix those if at all?

```
[info] No tests to run for Test / testOnly
[error] /Users/philippederome/workspace/forked-fp-foundation/exercises/src/test/scala/types/TypeTest.scala:61:33: diverging implicit expansion for type cats.kernel.Hash[A]
[error] starting with value catsKernelStdOrderForInt in trait IntInstances
[error]   checkAll("a + 0 == a", IsoLaws(aOrNothingToA[Int]))
[error]                                 ^
[error] /Users/philippederome/workspace/forked-fp-foundation/exercises/src/test/scala/types/TypeTest.scala:63:34: could not find implicit value for evidence parameter of type cats.kernel.Eq[Unit => Int]
[error]   checkAll("a ^ 1 ==  a", IsoLaws(power1[Int]))
[error]                                  ^
[error] two errors found
[error] (exercises / Test / compileIncremental) Compilation failed
[error] Total time: 3 s, completed 5-May-2019 6:20:57 PM
sbt:fp-foundation> 
```

See below for current Eq code that could work (you'd have to *scrutinize* this since a lot of them might belong with the artificial newtypes instead of here or vice-versa, also some implementations probably fail the smell test):

```
package exercises.typeclass

import cats.data.NonEmptyList
import exercises.functors.{Compose, Id}

trait Eq[A] {
  def eqv(x: A, y: A): Boolean

  def neqv(x: A, y: A): Boolean = !eqv(x, y)

}

object Eq {
  def apply[A](implicit ev: Eq[A]): Eq[A] = ev

  def by[@specialized A, @specialized B](f: A => B)(implicit ev: Eq[B]): Eq[A] =
    new Eq[A] {
      def eqv(x: A, y: A) = ev.eqv(f(x), f(y))
    }

  object syntax {

    implicit class EqSyntax[A](self: A) {
      def eqv(other: A)(implicit ev: Eq[A]): Boolean =
        ev.eqv(self, other)

      def ===(other: A)(implicit ev: Eq[A]): Boolean = eqv(other)

      def neqv(other: A)(implicit ev: Eq[A]): Boolean = !eqv(other)
    }

  }

  implicit val intEq: Eq[Int] = new Eq[Int] {
    def eqv(x: Int, y: Int): Boolean = x == y
  }

  implicit def listEq[A: Eq]: Eq[List[A]] = new Eq[List[A]] {
    def eqv(x: List[A], y: List[A]): Boolean = x.lengthCompare(y.length) == 0 &&
      x.zip(y).forall { case (a, b) => Eq[A].eqv(a, b) }
  }

  implicit def nelistEq[A: Eq]: Eq[NonEmptyList[A]] = new Eq[NonEmptyList[A]] {
    def eqv(x: NonEmptyList[A], y: NonEmptyList[A]): Boolean = (x, y) match {
      case (NonEmptyList(h1, t1), NonEmptyList(h2, t2)) =>
        val p = Eq[A]
        p.eqv(h1, h2) && listEq[A].eqv(t1, t2)
    }
  }

  implicit def optionEq[A: Eq]: Eq[Option[A]] = new Eq[Option[A]] {
    def eqv(x: Option[A], y: Option[A]): Boolean = (x, y) match {
      case (Some(a), Some(b)) => Eq[A].eqv(a, b)
      case (None, None) => true
      case _ => false
    }
  }

  implicit def idEq[A: Eq]: Eq[Id[A]] = new Eq[Id[A]] {
    def eqv(x: Id[A], y: Id[A]): Boolean =
      Eq[A].eqv(x.value, y.value)
  }

  implicit def eq[F[_], G[_], A](implicit ev: Eq[F[G[A]]]): Eq[Compose[F, G, A]] =
    Eq.by(_.getCompose)

  implicit def eitherEq[A: Eq, B: Eq]: Eq[Either[A, B]] = new Eq[Either[A, B]] {
    def eqv(x: Either[A, B], y: Either[A, B]): Boolean = (x, y) match {
      case (Left(a), Left(b)) => Eq[A].eqv(a, b)
      case (Right(a), Right(b)) => Eq[B].eqv(a, b)
      case _ => false
    }
  }

  implicit def tupleEq[A: Eq, B: Eq]: Eq[Tuple2[A, B]] = new Eq[Tuple2[A, B]] {
    def eqv(x: Tuple2[A, B], y: Tuple2[A, B]): Boolean =
      Eq[A].eqv(x._1, y._1) && Eq[B].eqv(x._2, y._2)
  }

  implicit def setEq[A: Eq]: Eq[Set[A]] = new Eq[Set[A]] {
    def eqv(x: Set[A], y: Set[A]): Boolean = x == y
  }

  implicit def vectorEq[A: Eq]: Eq[Vector[A]] = new Eq[Vector[A]] {
    def eqv(x: Vector[A], y: Vector[A]): Boolean = x == y
  }

  implicit def mapEq[A: Eq, B: Eq]: Eq[Map[A, B]] = new Eq[Map[A, B]] {
    def eqv(x: Map[A, B], y: Map[A, B]): Boolean = x == y
  }

  implicit val dblEq: Eq[Double] = new Eq[Double] {
    def eqv(x: Double, y: Double): Boolean = x == y
  }

  implicit val unitEq: Eq[Unit] = new Eq[Unit] {
    def eqv(x: Unit, y: Unit): Boolean = true
  }

  implicit val boolEq: Eq[Boolean] = new Eq[Boolean] {
    def eqv(x: Boolean, y: Boolean): Boolean = x == y
  }

  implicit val stringEq: Eq[String] = new Eq[String] {
    def eqv(x: String, y: String): Boolean = x == y
  }
}
```
