### ISSUE TITLE
Type too small should be too wide, no?

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#25]
https://julien-truffaut.github.io/fp-foundation/Type.html#21 22 23

**Comment by julien-truffaut** [comment]
No it is meant to be too small but I am not happy with examples.

For the size, I use it to say that you could have a collection with more than Maint item, especially nowadays with big data. You are right that it cannot be negative so we should use either a positive long or something like Nat

So far the best example I found was the optional error parsing for Json. In this case we lose all parsing error information, we just know that it failed.

**Comment by phderome** [comment]
It could be clearer, that is all.
