### ISSUE TITLE
confusing laws notation Functors#20

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#39]
Symbol `=~` is confusing and seems to denote isomorphism. In same context, code FLaws.scala uses productL and productR underlying operators `*>` and `<*` with the latter two symbols being differentiated (not a symmetric operator like `=~` or `*=` or whatever).

**Comment by julien-truffaut** [comment]
I got your point. I agree it is not ideal now, I am trying to find the right balance between the number of concepts introduced, clarity, easy to remember... Next, I want to use diagrams to illustrate each law, will see how it goes

**Comment by julien-truffaut** [comment]
I feel it is less confusing now with the diagrams, please re-open if you still think it is unclear
