### ISSUE TITLE
coherence functor (applicative law) slide 31

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#43]
https://julien-truffaut.github.io/fp-foundation/Functors#31

You have `f` on RHS leading to arbitrary `F[B]` however the LHS yields `fa` in my opinion.

**Comment by phderome** [comment]
Maybe you just need to call `f` on LHS as below but as of now you don't.
` fa.map2(unit)((a, _) => f(a)) == fa.map(f)`

**Comment by julien-truffaut** [comment]
Good catch
