### ISSUE TITLE
Functors #49 could be clearer (and previous ones from same template)

### ISSUE THREAD

**Issue by phderome** [julien-truffaut/fp-foundation#44]
https://julien-truffaut.github.io/fp-foundation/Functors#49

- notation of `:=` in line with `vectorSize`, I don't follow what is meant here.
- coherence law: RHS `fa.size`. Is that `size` simply a conceptual one in our minds or literally meant to be a API call?
- `vectorSize` is introduced but not referenced later on on slide. Why?
- How does coherence Law relate to `vectorTraverse` if at all? If not why do we bring in `vectorTraverse`?

**Comment by julien-truffaut** [comment]
`vectorSize` should be `sizeDefault`, I forgot to rename it.

I guess I could used `=` instead of `:=`. This line is to show how code expands.

I should change the law to be:

```scala
forAll(vec: Vector[A] => sizeDefault(vec) == vec.size)
```

`vec.size` is the `size` from standard library

**Comment by julien-truffaut** [comment]
@phderome is it better now? would you change something else?

**Comment by phderome** [comment]
Better, yes.

RHS of law should be vectorTraverse.size(vec) no?

Also the law should be valid for all Traverse, no? Is vector simply a natural example to present or should we understand that the law extends beyond vectors?

**Comment by julien-truffaut** [comment]
good questions. Rather than explaining here, I tried to update the slides to clarify these points. Please let me know if it worked.

**Comment by phderome** [comment]
it works yes
